name: Upload Website to S3

on:
  push:
    branches:
      - test-workflow
  workflow_dispatch:

env:
  AWS_REGION: 'eu-north-1'
  SOURCE_DIR: 'website'
  AWS_S3_BUCKET: 'test-cloud-resume-aleksander' # Statisch auf den Test-Bucket gesetzt

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository
      - uses: actions/checkout@v3

      # 2. Debugging: Check environment variables and files
      - run: echo "AWS_S3_BUCKET=$AWS_S3_BUCKET"
      - run: echo "SOURCE_DIR=$SOURCE_DIR"
      - run: ls $SOURCE_DIR

      # 3. Sync files to S3
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete # Entferne die --acl public-read Option
        env:
          AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}

